[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# So /api/* can map to Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200